### ISSUE TITLE
Submit upstream

### ISSUE THREAD

**Issue by mbrevda** [flaper87/cdr_mongodb#3]
This module looks great. Would you submit it back to Digium for inclusion in the official  Asterisk release?

**Comment by mbrevda** [comment]
I found your ticket on issues.asterisk.org. Shame about the licensing issues, thanks for trying!

Btw, did you contact 10gen.com to see if they would relese the driver as GPL?

**Comment by flaper87** [comment]
Yup, I'm involved in mongodb's community. I'm afraid that's not going to happen :cry: 

I guess, it's up to us to push it to the community. Thanks for your comment

**Comment by mbrevda** [comment]
As a last resort: are there no gpl'd c drivers available?
